version: '2.4'
services:
  server: 
    image: node:alpine
    env_file: .env
    working_dir: /app
    restart: unless-stopped
    ports:
      - "7000:7000"
    command: "./wait-for-mongo.sh"
    depends_on:
      - "mongo"
    links:
      - "mongo:mongo"
    volumes:
      - './server:/app'

  client:
    build: 
      context: ./client
      target: client-prod
    ports:
      - "8888:80"
    links:
      - "server:server"

  mongo:
    restart: unless-stopped
    image: mongo:latest
    volumes:
      - './mongo:/data/db'
    command: "mongod --wiredTigerCacheSizeGB 0.4"
    mem_limit: 500m
